services:
  metad0:
    image: vesoft/nebula-metad:${NEBULA_VERSION}
    container_name: nebula-metad0
    ports:
      - "9559:9559"
      - "19559:19559"
      - "19569:19569"
    volumes:
      - nebula-metad0:/usr/local/nebula/data/meta
    command:
      - nebula-metad
      - --meta_server_addrs=metad0:9559
      - --local_ip=metad0
      - --ws_ip=metad0
      - --port=9559
      - --ws_http_port=19559
      - --data_path=/usr/local/nebula/data/meta

  storaged0:
    image: vesoft/nebula-storaged:${NEBULA_VERSION}
    container_name: nebula-storaged0
    depends_on:
      - metad0
    ports:
      - "9779:9779"
      - "19779:19779"
      - "19769:19769"
    volumes:
      - nebula-storaged0:/usr/local/nebula/data/storage
    command:
      - nebula-storaged
      - --meta_server_addrs=metad0:9559
      - --local_ip=storaged0
      - --ws_ip=storaged0
      - --port=9779
      - --ws_http_port=19779
      - --data_path=/usr/local/nebula/data/storage

  graphd:
    image: vesoft/nebula-graphd:${NEBULA_VERSION}
    container_name: nebula-graphd
    depends_on:
      - metad0
      - storaged0
    ports:
      - "9669:9669"
      - "19669:19669"
    volumes:
      - ../graph/seed:/seed:ro
    command:
      - nebula-graphd
      - --meta_server_addrs=metad0:9559
      - --port=9669
      - --ws_http_port=19669

volumes:
  nebula-metad0:
  nebula-storaged0:
